# Generated by Django 4.1.1 on 2022-09-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring_google_tab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletab',
            name='cost_rubles',
            field=models.IntegerField(verbose_name='стоимость, ₽'),
        ),
    ]
